name: API Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install FastAPI dependencies
        working-directory: api-server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        working-directory: api-server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          echo "Waiting for FastAPI to start..."
          for i in {1..15}; do
            curl -s http://localhost:8000/health && echo "FastAPI is up!" && break
            sleep 2
          done

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Maven tests
        run: mvn clean test

      - name: Show Test Reports (if any)
        if: failure()
        run: cat target/surefire-reports/*.txt || echo "No reports found"
