name: Bookstore API Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install FastAPI app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Run FastAPI server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build and run tests
        run: mvn clean test

      - name: Show test results
        run: cat target/surefire-reports/*.txt || true
